Add support for BarometricPressureSensor
mozilla-iot/gateway pull request #2586
Opened 2020-09-06 21:57 UTC by tim-hellhake

resolves #2577

2020-09-06 22:14 UTC, mrstegeman requested changes
No German translation?

2020-09-06 22:14 UTC, mrstegeman commented on static/js/schema-impl/capability/barometric-pressure-sensor.js
> + * Humidity sensor.
Update comment.

2020-09-07 20:16 UTC, mrstegeman approved these changes

2020-09-07 20:17 UTC, tim-hellhake commented
> No German translation?

I have no explanation of how I could miss that :joy:

2020-09-07 20:21 UTC, merged